// DO NOT EDIT — generated by scripts/gen-msw-handlers.mjs
// Regenerate via `pnpm api:mocks` after editing api/openapi.yaml or
// api/examples/. CI fails if this file drifts from the spec.

import { http, HttpResponse, delay } from 'msw';
import type { RequestHandler } from 'msw';

const PROFILE =
  (typeof import.meta !== 'undefined' &&
    (import.meta as unknown as { env?: Record<string, string> }).env
      ?.CLAW_MOCK_PROFILE) ||
  (typeof process !== 'undefined' && process.env?.CLAW_MOCK_PROFILE) ||
  'happy';

const ERROR_CODES = [
  'INVALID_INTERVAL',
  'SYMBOL_NOT_FOUND',
  'INVALID_RANGE',
  'COMPLIANCE_FAILED',
  'SANDBOX_ERROR',
  'SANDBOX_TIMEOUT',
  'DATA_UNAVAILABLE',
  'UPSTREAM_UNREACHABLE',
  'INTERNAL_ERROR',
] as const;

function maybeError() {
  if (PROFILE !== 'chaos') return null;
  if (Math.random() >= 0.15) return null;
  const code = ERROR_CODES[Math.floor(Math.random() * ERROR_CODES.length)];
  const status = code === 'INTERNAL_ERROR' || code === 'UPSTREAM_UNREACHABLE' ? 500 : 400;
  return HttpResponse.json(
    { error: { code, message: 'simulated chaos', details: {} } },
    { status },
  );
}

async function maybeDelay() {
  if (PROFILE === 'slow') {
    await delay(500 + Math.floor(Math.random() * 1000));
  }
}


export const handlers: RequestHandler[] = [
  // getHealth
  http.get('*/healthz', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"status":"ok"});
  }),
  // getKlines
  http.get('*/api/klines', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json([{"ts":1744416000,"o":64200.5,"h":64480,"l":64120,"c":64412.8,"v":1234.56,"qv":79450000},{"ts":1744419600,"o":64412.8,"h":64590,"l":64280,"c":64510.2,"v":1102.33,"qv":70950000},{"ts":1744423200,"o":64510.2,"h":64720.5,"l":64440,"c":64688.1,"v":987.11,"qv":63800000},{"ts":1744426800,"o":64688.1,"h":64890,"l":64620,"c":64795.7,"v":1510.42,"qv":97950000},{"ts":1744430400,"o":64795.7,"h":64850,"l":64640,"c":64701.3,"v":900.75,"qv":null}]);
  }),
  // listSymbols
  http.get('*/api/symbols', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"items":[{"symbol":"BTC_USDT","market":"futures","rank":1,"volume_24h_quote":5128061921,"status":"active","updated_at":1744416000},{"symbol":"ETH_USDT","market":"futures","rank":2,"volume_24h_quote":2940715000,"status":"active","updated_at":1744416000},{"symbol":"SOL_USDT","market":"futures","rank":3,"volume_24h_quote":1620550000,"status":"active","updated_at":1744416000},{"symbol":"DOGE_USDT","market":"futures","rank":4,"volume_24h_quote":880330000,"status":"active","updated_at":1744416000},{"symbol":"AVAX_USDT","market":"futures","rank":5,"volume_24h_quote":510220000,"status":"active","updated_at":1744416000}],"next_cursor":"eyJyYW5rIjo1LCJzeW1ib2wiOiJBVkFYX1VTRFQifQ=="});
  }),
  // listGaps
  http.get('*/api/gaps', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json([{"id":101,"symbol":"BTC_USDT","market":"futures","interval":"5m","gap_from":1744300200,"gap_to":1744301400,"missing_bars":3,"status":"detected","retry_count":0,"error":null},{"id":102,"symbol":"XYZ_USDT","market":"futures","interval":"1h","gap_from":1744200000,"gap_to":1744210800,"missing_bars":3,"status":"unrecoverable","retry_count":3,"error":"s3 object not found"}]);
  }),
  // createStrategy
  http.post('*/api/strategies', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"id":"00000000-0000-0000-0000-000000000001","name":"SMA Crossover v3"});
  }),
  // listStrategies
  http.get('*/api/strategies', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"items":[{"id":"00000000-0000-0000-0000-000000000001","name":"SMA Crossover v3","code_type":"strategy","code":"from claw.strategy import Strategy\n\nclass MyStrategy(Strategy):\n    def setup(self):\n        self.fast = self.indicator('SMA', period=10)\n        self.slow = self.indicator('SMA', period=30)\n    def on_bar(self, bar):\n        if self.fast.iloc[-1] > self.slow.iloc[-1]:\n            self.buy(size=1)\n        else:\n            self.sell(size=1)\n","params_schema":{"fast":{"type":"int","default":10},"slow":{"type":"int","default":30}},"current_version":3,"created_at":1743768000,"updated_at":1744416000},{"id":"00000000-0000-0000-0000-000000000002","name":"Bollinger Breakout","code_type":"strategy","code":"from claw.strategy import Strategy\n\nclass BB(Strategy):\n    def on_bar(self, bar):\n        pass\n","params_schema":null,"current_version":1,"created_at":1743509000,"updated_at":1744330000}],"next_cursor":null});
  }),
  // getStrategy
  http.get('*/api/strategies/:id', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"id":"00000000-0000-0000-0000-000000000001","name":"SMA Crossover v3","code_type":"strategy","code":"from claw.strategy import Strategy\n\nclass MyStrategy(Strategy):\n    def setup(self):\n        self.fast = self.indicator('SMA', period=10)\n        self.slow = self.indicator('SMA', period=30)\n    def on_bar(self, bar):\n        if self.fast.iloc[-1] > self.slow.iloc[-1]:\n            self.buy(size=1)\n        else:\n            self.sell(size=1)\n","params_schema":{"fast":{"type":"int","default":10},"slow":{"type":"int","default":30}},"current_version":3,"created_at":1743768000,"updated_at":1744416000});
  }),
  // startBacktest
  http.post('*/api/backtest/start', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"task_id":"00000000-0000-0000-0000-000000000010","status":"pending","started_at":1744416000});
  }),
  // getBacktestStatus
  http.get('*/api/backtest/status/:task_id', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"task_id":"00000000-0000-0000-0000-000000000010","status":"running","progress":{"phase":"sandbox","done":45,"total":100},"started_at":1744416000});
  }),
  // getBacktestResult
  http.get('*/api/backtest/result/:task_id', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"task_id":"00000000-0000-0000-0000-000000000010","status":"done","started_at":1744416000,"finished_at":1744416120,"result":{"metrics":{"total_return":12.5,"sharpe":1.42,"max_drawdown":-8.2,"win_rate":56,"profit_factor":1.78,"avg_trade":2.1,"total_trades":48},"equity_curve":[{"ts":1744329600,"value":10000},{"ts":1744372800,"value":10150},{"ts":1744416000,"value":11250}],"trades":[{"id":"t-1","symbol":"BTC_USDT","side":"long","entry_ts":1744329600,"entry_price":62100,"exit_ts":1744351200,"exit_price":63450,"pnl_pct":2.17,"duration_hours":6},{"id":"t-2","symbol":"BTC_USDT","side":"short","entry_ts":1744362000,"entry_price":63900,"exit_ts":1744372800,"exit_price":63200,"pnl_pct":1.1,"duration_hours":3}]}});
  }),
  // listBacktestHistory
  http.get('*/api/backtest/history', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"items":[{"id":"00000000-0000-0000-0000-000000000010","strategy_id":"00000000-0000-0000-0000-000000000001","status":"done","mode":"single","started_at":1744416000,"finished_at":1744416120,"summary_return":12.5},{"id":"00000000-0000-0000-0000-000000000011","strategy_id":"00000000-0000-0000-0000-000000000001","status":"done","mode":"single","started_at":1744329600,"finished_at":1744329720,"summary_return":-2.1}],"next_cursor":null});
  }),
  // startScreener
  http.post('*/api/screener/start', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"task_id":"00000000-0000-0000-0000-000000000020","status":"pending","started_at":1744416000});
  }),
  // getScreenerResult
  http.get('*/api/screener/result/:task_id', async () => {
    await maybeDelay();
    const chaos = maybeError();
    if (chaos) return chaos;
    return HttpResponse.json({"task_id":"00000000-0000-0000-0000-000000000020","status":"done","started_at":1744416000,"finished_at":1744416045,"result":{"results":[{"symbol":"BTC_USDT","passed":true,"score":0.95,"rank":1,"volume_24h_quote":5128061921},{"symbol":"ETH_USDT","passed":true,"score":0.88,"rank":2,"volume_24h_quote":2940715000},{"symbol":"SOL_USDT","passed":true,"score":0.76,"rank":3,"volume_24h_quote":1620550000},{"symbol":"XRP_USDT","passed":false,"score":0.12,"rank":15,"volume_24h_quote":210000000},{"symbol":"LOW_USDT","passed":false,"score":0.02,"rank":280,"volume_24h_quote":450000}]}});
  }),
];

export const operationIds = ["getHealth","getKlines","listSymbols","listGaps","createStrategy","listStrategies","getStrategy","startBacktest","getBacktestStatus","getBacktestResult","listBacktestHistory","startScreener","getScreenerResult"] as const;
