// DO NOT EDIT — this file is generated by scripts/gen-api-types.mjs
// Regenerate via `pnpm api:types` (or `npm run api:types`) after any
// change to api/openapi.yaml. CI fails if this file is out of sync with
// the spec.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/klines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch K-lines for a symbol */
        get: operations["getKlines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List symbols (paginated) */
        get: operations["listSymbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List detected data gaps */
        get: operations["listGaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List strategies (paginated) */
        get: operations["listStrategies"];
        put?: never;
        /** Create a strategy */
        post: operations["createStrategy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a strategy by id */
        get: operations["getStrategy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a backtest */
        post: operations["startBacktest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll backtest status */
        get: operations["getBacktestStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/result/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch backtest result */
        get: operations["getBacktestResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List past backtests (paginated) */
        get: operations["listBacktestHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a screener */
        post: operations["startScreener"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/result/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll / fetch screener result */
        get: operations["getScreenerResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Canonical lifecycle state for any long-running server task.
         * @enum {string}
         */
        TaskStatus: "pending" | "running" | "done" | "failed" | "cancelled";
        /** @description Optional progress hint on a running task. Phase values are operation-specific (e.g. "sweep", "synthesize", "sandbox", "aggregate", "backtest", "fetch", "llm"). */
        TaskProgress: {
            phase?: string;
            done?: number;
            total?: number;
        };
        /** @description Canonical envelope for every long-running operation. `result` is present only when `status === "done"`; `error` only when `status === "failed"`. Concrete operations narrow `result` via `allOf` + per-operation schema. */
        TaskResponse: {
            /** Format: uuid */
            task_id: string;
            status: components["schemas"]["TaskStatus"];
            progress?: components["schemas"]["TaskProgress"];
            /** @description Operation-specific result; narrowed by concrete endpoint. */
            result?: unknown;
            error?: components["schemas"]["ErrorBody"];
            /** @description Unix seconds when the task was accepted. */
            started_at: number;
            /** @description Unix seconds when the task reached a terminal state. */
            finished_at?: number | null;
        };
        /**
         * @description Predefined error-code dictionary (see `api/errors.md`). Keep
         *     additions conservative — removing a code is breaking; adding
         *     is safe.
         * @enum {string}
         */
        ErrorCode: "INVALID_INTERVAL" | "INVALID_SYMBOL" | "INVALID_RANGE" | "SYMBOL_NOT_FOUND" | "STRATEGY_NOT_FOUND" | "BACKTEST_NOT_FOUND" | "SCREENER_NOT_FOUND" | "TASK_NOT_FOUND" | "COMPLIANCE_FAILED" | "SANDBOX_ERROR" | "SANDBOX_TIMEOUT" | "DATA_UNAVAILABLE" | "RATE_LIMITED" | "UPSTREAM_UNREACHABLE" | "INTERNAL_ERROR";
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** @description Human-readable; not the identifier. Use `code` for branching. */
            message: string;
            /** @description Code-specific payload. See errors.md for per-code keys. */
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** @description Opaque cursor-based pagination envelope. Server encodes an internal cursor as base64 JSON; clients treat it as a string. */
        Pagination: {
            next_cursor: string | null;
        };
        /** @enum {string} */
        Interval: "5m" | "15m" | "30m" | "1h" | "4h" | "1d";
        /** @enum {string} */
        Market: "futures";
        Kline: {
            /** @description Unix seconds at the open of the bar. */
            ts: number;
            o: number;
            h: number;
            l: number;
            c: number;
            v: number;
            /** @description Quote volume (USDT). Null when unavailable. */
            qv?: number | null;
        };
        Symbol: {
            symbol: string;
            market: components["schemas"]["Market"];
            rank?: number | null;
            volume_24h_quote?: number | null;
            /** @enum {string} */
            status: "active" | "inactive";
            /** @description Unix seconds. */
            updated_at?: number;
        };
        Gap: {
            id?: number;
            symbol: string;
            market: components["schemas"]["Market"];
            interval: components["schemas"]["Interval"];
            /** @description Unix seconds. */
            gap_from: number;
            /** @description Unix seconds. */
            gap_to: number;
            missing_bars: number;
            /** @enum {string} */
            status: "detected" | "repairing" | "repaired" | "unrecoverable" | "skipped";
            retry_count?: number;
            error?: string | null;
        };
        Strategy: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            code_type: "strategy" | "screener";
            code: string;
            params_schema?: {
                [key: string]: unknown;
            } | null;
            /** @description Latest version number (filled after `strategy-versions` capability lands). */
            current_version?: number;
            created_at: number;
            updated_at: number;
        };
        BacktestConfig: {
            symbols: string[];
            interval: components["schemas"]["Interval"];
            /** @description Unix seconds. */
            from: number;
            /** @description Unix seconds. */
            to: number;
            /** @description Optional. Backend defaults to 10000 when omitted. */
            initial_capital?: number;
            /** @description Optional. Backend defaults to 0.0006. */
            commission?: number;
            /** @description Optional. Backend defaults to 0.0001. */
            slippage?: number;
        };
        /** @description Summary metrics derived from an equity curve. */
        MetricsBlock: {
            total_return?: number | null;
            sharpe?: number | null;
            max_drawdown?: number | null;
            win_rate?: number | null;
            profit_factor?: number | null;
            avg_trade?: number | null;
            total_trades?: number;
        };
        EquityPoint: {
            /** @description Unix seconds */
            ts: number;
            value: number;
        };
        Trade: {
            id: string;
            symbol: string;
            /** @enum {string} */
            side: "long" | "short";
            entry_ts: number;
            entry_price: number;
            exit_ts?: number | null;
            exit_price?: number | null;
            pnl_pct?: number | null;
            duration_hours?: number | null;
        };
        /**
         * @description Result payload for a done backtest task. The current contract
         *     describes the single-mode shape. Multi-symbol + preview/deep
         *     extensions live in the follow-up `api-contract-new-capabilities`.
         */
        BacktestResult: {
            metrics?: components["schemas"]["MetricsBlock"];
            equity_curve?: components["schemas"]["EquityPoint"][];
            trades?: components["schemas"]["Trade"][];
        };
        BacktestHistoryItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            strategy_id?: string | null;
            status: components["schemas"]["TaskStatus"];
            /** @default single */
            mode: string;
            started_at: number;
            finished_at?: number | null;
            summary_return?: number | null;
        };
        ScreenerRowResult: {
            symbol: string;
            passed: boolean;
            score: number;
            rank?: number | null;
            volume_24h_quote?: number | null;
        };
        ScreenerResult: {
            results: components["schemas"]["ScreenerRowResult"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    getKlines: {
        parameters: {
            query: {
                symbol: string;
                interval: components["schemas"]["Interval"];
                from?: number;
                to?: number;
                market?: components["schemas"]["Market"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered K-lines (ascending by ts) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kline"][];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSymbols: {
        parameters: {
            query?: {
                market?: components["schemas"]["Market"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated symbols */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items: components["schemas"]["Symbol"][];
                    };
                };
            };
        };
    };
    listGaps: {
        parameters: {
            query?: {
                symbol?: string;
                interval?: components["schemas"]["Interval"];
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching gaps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gap"][];
                };
            };
        };
    };
    listStrategies: {
        parameters: {
            query?: {
                code_type?: "strategy" | "screener";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated strategies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items: components["schemas"]["Strategy"][];
                    };
                };
            };
        };
    };
    createStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    code_type: "strategy" | "screener";
                    code: string;
                    params_schema?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                    };
                };
            };
        };
    };
    getStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strategy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startBacktest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                    config: components["schemas"]["BacktestConfig"];
                    /** Format: uuid */
                    strategy_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Task accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBacktestStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status envelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    getBacktestResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full result (embedded when status=done) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"] & {
                        result?: components["schemas"]["BacktestResult"];
                    };
                };
            };
        };
    };
    listBacktestHistory: {
        parameters: {
            query?: {
                strategy_id?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items: components["schemas"]["BacktestHistoryItem"][];
                    };
                };
            };
        };
    };
    startScreener: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                    config?: {
                        market?: components["schemas"]["Market"];
                        /** @default 365 */
                        lookback_days?: number;
                    };
                    /** Format: uuid */
                    strategy_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Task accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    getScreenerResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task envelope (result present when done) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"] & {
                        result?: components["schemas"]["ScreenerResult"];
                    };
                };
            };
        };
    };
}
