// DO NOT EDIT — this file is generated by scripts/gen-api-types.mjs
// Regenerate via `pnpm api:types` (or `npm run api:types`) after any
// change to api/openapi.yaml. CI fails if this file is out of sync with
// the spec.

/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/klines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch K-lines for a symbol */
        get: operations["getKlines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List symbols (paginated) */
        get: operations["listSymbols"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List detected data gaps */
        get: operations["listGaps"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List strategies (paginated) */
        get: operations["listStrategies"];
        put?: never;
        /** Create a strategy */
        post: operations["createStrategy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a strategy by id */
        get: operations["getStrategy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update workspace-draft fields of a strategy
         * @description Updates `draft_code`, `draft_symbols`, and/or `last_backtest`
         *     without touching the saved zone (`saved_code`, `saved_symbols`,
         *     `saved_at`).  The dedicated POST `/save` endpoint is the only
         *     way to mutate the saved fields — that separation guarantees
         *     chat-driven edits never accidentally clobber a deliberate save.
         */
        patch: operations["patchStrategyDraft"];
        trace?: never;
    };
    "/api/strategies/{id}/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Snapshot draft → saved
         * @description Atomically copies `draft_code` → `saved_code`, `draft_symbols` →
         *     `saved_symbols`, sets `saved_at = now()`, clears `is_archived_draft`,
         *     and (if `name` is supplied) updates the strategy name.  This is
         *     the ONLY endpoint that may mutate saved-zone fields.
         */
        post: operations["saveStrategy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{id}/archive_draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a strategy session as an archived draft
         * @description Sets `is_archived_draft = true` so the row sinks to the
         *     "归档草稿" filter in the library tab.  Used by the desktop
         *     client when the user presses "+ 创建新策略" while the active
         *     session is dirty: the previous strategy is preserved as a
         *     recoverable draft instead of being silently lost.
         */
        post: operations["archiveStrategyDraft"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submit a backtest
         * @description Validates and dispatches a backtest job.  The code goes through
         *     two gates before execution:
         *
         *       - Gate 1 (AST): forbidden-module/builtins check → 400 `COMPLIANCE_FAILED` on fail.
         *       - Gate 2 (AI review): DeepSeek security+correctness review → 403 `AI_REJECTED` on fail,
         *         503 `AI_REVIEW_UNAVAILABLE` when the reviewer is down.
         *
         *     Rejections at either gate short-circuit: no row is written to `claw.backtest_runs`.
         */
        post: operations["startBacktest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/status/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll backtest status */
        get: operations["getBacktestStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/result/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch backtest result */
        get: operations["getBacktestResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/backtest/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List past backtests (paginated) */
        get: operations["listBacktestHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run a screener
         * @description Symmetric to `/api/backtest/start`: Gate 1 (AST) + Gate 2 (AI review)
         *     both run before dispatch.  See that endpoint for rejection semantics.
         */
        post: operations["startScreener"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener/result/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll / fetch screener result */
        get: operations["getScreenerResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/symbols/{symbol}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get metadata for a single symbol */
        get: operations["getSymbolMetadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all versions of a strategy (newest first) */
        get: operations["listStrategyVersions"];
        put?: never;
        /** Append a new version to a strategy */
        post: operations["createStrategyVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{id}/versions/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one specific version */
        get: operations["getStrategyVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/optimlens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit an OptimLens parameter-sweep + synthesis task */
        post: operations["startOptimLens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/optimlens/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll / fetch OptimLens task */
        get: operations["getOptimLensResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a signal-review task for a backtest's signals */
        post: operations["startSignalReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/signals/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll / fetch SignalReview task */
        get: operations["getSignalReviewResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analysis/trade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Synchronous per-trade explanation */
        post: operations["explainTrade"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/engine/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Backend self-description for the Settings page */
        get: operations["getEngineStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description Canonical lifecycle state for any long-running server task.
         * @enum {string}
         */
        TaskStatus: "pending" | "running" | "done" | "failed" | "cancelled";
        /** @description Optional progress hint on a running task. Phase values are operation-specific (e.g. "sweep", "synthesize", "sandbox", "aggregate", "backtest", "fetch", "llm"). */
        TaskProgress: {
            phase?: string;
            done?: number;
            total?: number;
        };
        /** @description Canonical envelope for every long-running operation. `result` is present only when `status === "done"`; `error` only when `status === "failed"`. Concrete operations narrow `result` via `allOf` + per-operation schema. */
        TaskResponse: {
            /** Format: uuid */
            task_id: string;
            status: components["schemas"]["TaskStatus"];
            progress?: components["schemas"]["TaskProgress"];
            /** @description Operation-specific result; narrowed by concrete endpoint. */
            result?: unknown;
            error?: components["schemas"]["ErrorBody"];
            /** @description Unix seconds when the task was accepted. */
            started_at: number;
            /** @description Unix seconds when the task reached a terminal state. */
            finished_at?: number | null;
        };
        /**
         * @description Predefined error-code dictionary (see `api/errors.md`). Keep
         *     additions conservative — removing a code is breaking; adding
         *     is safe.
         * @enum {string}
         */
        ErrorCode: "INVALID_INTERVAL" | "INVALID_SYMBOL" | "INVALID_RANGE" | "SYMBOL_NOT_FOUND" | "STRATEGY_NOT_FOUND" | "STRATEGY_VERSION_NOT_FOUND" | "BACKTEST_NOT_FOUND" | "SCREENER_NOT_FOUND" | "TASK_NOT_FOUND" | "COMPLIANCE_FAILED" | "AI_REJECTED" | "AI_REVIEW_UNAVAILABLE" | "SANDBOX_ERROR" | "SANDBOX_TIMEOUT" | "DATA_UNAVAILABLE" | "RATE_LIMITED" | "UPSTREAM_UNREACHABLE" | "INTERNAL_ERROR" | "PARAM_GRID_TOO_LARGE" | "LLM_PROVIDER_FAILED" | "LLM_BUDGET_EXCEEDED";
        ErrorBody: {
            code: components["schemas"]["ErrorCode"];
            /** @description Human-readable; not the identifier. Use `code` for branching. */
            message: string;
            /** @description Code-specific payload. See errors.md for per-code keys. */
            details?: {
                [key: string]: unknown;
            };
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** @description Opaque cursor-based pagination envelope. Server encodes an internal cursor as base64 JSON; clients treat it as a string. */
        Pagination: {
            next_cursor: string | null;
        };
        /** @enum {string} */
        Interval: "5m" | "15m" | "30m" | "1h" | "4h" | "1d";
        /** @enum {string} */
        Market: "futures";
        Kline: {
            /** @description Unix seconds at the open of the bar. */
            ts: number;
            o: number;
            h: number;
            l: number;
            c: number;
            v: number;
            /** @description Quote volume (USDT). Null when unavailable. */
            qv?: number | null;
        };
        Symbol: {
            symbol: string;
            market: components["schemas"]["Market"];
            rank?: number | null;
            volume_24h_quote?: number | null;
            /** @enum {string} */
            status: "active" | "inactive";
            /** @description Unix seconds. */
            updated_at?: number;
        };
        Gap: {
            id?: number;
            symbol: string;
            market: components["schemas"]["Market"];
            interval: components["schemas"]["Interval"];
            /** @description Unix seconds. */
            gap_from: number;
            /** @description Unix seconds. */
            gap_to: number;
            missing_bars: number;
            /** @enum {string} */
            status: "detected" | "repairing" | "repaired" | "unrecoverable" | "skipped";
            retry_count?: number;
            error?: string | null;
        };
        /**
         * @description Stored user-submitted strategy.  After unified-strategy-workspace
         *     (migration 006) a strategy carries a workspace zone (chat-driven
         *     draft fields) plus a saved zone (snapshot taken when the user
         *     clicks 保存策略).  Legacy `code_type` is omitempty on new rows.
         */
        Strategy: {
            /** Format: uuid */
            id: string;
            name: string;
            /**
             * @description Legacy discriminator; not set on rows created via the unified workspace.
             * @enum {string}
             */
            code_type?: "strategy" | "screener";
            code: string;
            params_schema?: {
                [key: string]: unknown;
            } | null;
            /** @description Latest version number (filled after `strategy-versions` capability lands). */
            current_version?: number;
            created_at: number;
            updated_at: number;
            /** @description Latest in-flight strategy code from the chat workspace. */
            draft_code?: string | null;
            /** @description Latest in-flight symbol universe. */
            draft_symbols?: string[] | null;
            last_backtest?: components["schemas"]["LastBacktestSummary"];
            saved_code?: string | null;
            saved_symbols?: string[] | null;
            /** @description Unix seconds of the last 保存策略 action.  Null until first save. */
            saved_at?: number | null;
            /**
             * @description True when the user pressed "+ 创建新策略" while this session was
             *     dirty.  Such rows still appear in the library under the
             *     "归档草稿" filter.
             * @default false
             */
            is_archived_draft: boolean;
        };
        /**
         * @description Cached backtest summary stored on the strategy so re-opening it
         *     shows the most recent run without re-dispatching.  The summary
         *     payload is opaque on this surface (key:value of metric).
         */
        LastBacktestSummary: {
            /** Format: uuid */
            task_id: string;
            summary: {
                [key: string]: unknown;
            };
            /** @description Unix seconds when the backtest finished. */
            ran_at: number;
        };
        /**
         * @description Body of PATCH /api/strategies/{id}.  Workspace-zone only — saved
         *     fields are NOT touched by this endpoint.  Any omitted field
         *     leaves the corresponding column unchanged.
         */
        PatchStrategyDraftBody: {
            draft_code?: string;
            draft_symbols?: string[];
            last_backtest?: components["schemas"]["LastBacktestSummary"];
        };
        /**
         * @description Body of POST /api/strategies/{id}/save.  `name` is optional;
         *     sent on the FIRST save (when strategy.name is null and the user
         *     just typed one in the save dialog).
         */
        SaveStrategyBody: {
            name?: string;
        };
        BacktestConfig: {
            symbols: string[];
            interval: components["schemas"]["Interval"];
            /** @description Unix seconds. */
            from: number;
            /** @description Unix seconds. */
            to: number;
            /** @description Optional. Backend defaults to 10000 when omitted. */
            initial_capital?: number;
            /** @description Optional. Backend defaults to 0.0006. */
            commission?: number;
            /** @description Optional. Backend defaults to 0.0001. */
            slippage?: number;
        };
        /** @description Summary metrics derived from an equity curve. */
        MetricsBlock: {
            total_return?: number | null;
            sharpe?: number | null;
            max_drawdown?: number | null;
            win_rate?: number | null;
            profit_factor?: number | null;
            avg_trade?: number | null;
            total_trades?: number;
        };
        EquityPoint: {
            /** @description Unix seconds */
            ts: number;
            value: number;
        };
        Trade: {
            id: string;
            symbol: string;
            /** @enum {string} */
            side: "long" | "short";
            entry_ts: number;
            entry_price: number;
            exit_ts?: number | null;
            exit_price?: number | null;
            pnl_pct?: number | null;
            duration_hours?: number | null;
        };
        /**
         * @description Result payload for a done backtest task. The current contract
         *     describes the single-mode shape. Multi-symbol + preview/deep
         *     extensions live in the follow-up `api-contract-new-capabilities`.
         */
        BacktestResult: {
            metrics?: components["schemas"]["MetricsBlock"];
            equity_curve?: components["schemas"]["EquityPoint"][];
            trades?: components["schemas"]["Trade"][];
        };
        BacktestHistoryItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            strategy_id?: string | null;
            status: components["schemas"]["TaskStatus"];
            /** @default single */
            mode: string;
            started_at: number;
            finished_at?: number | null;
            summary_return?: number | null;
        };
        ScreenerRowResult: {
            symbol: string;
            passed: boolean;
            score: number;
            rank?: number | null;
            volume_24h_quote?: number | null;
        };
        ScreenerResult: {
            results: components["schemas"]["ScreenerRowResult"][];
        };
        /**
         * @description Mode drives default lookback (preview=7d, deep=180d).
         * @enum {string}
         */
        BacktestMode: "preview" | "deep";
        MonthlyPoint: {
            /** @description YYYY-MM */
            month: string;
            return_pct: number;
        };
        Signal: {
            signal_id: string;
            symbol: string;
            ts: number;
            /** @enum {string} */
            kind: "long" | "short" | "flat";
            indicators?: {
                [key: string]: number;
            };
        };
        /** @description Per-symbol breakdown of a multi-symbol backtest. */
        SymbolResult: {
            metrics?: components["schemas"]["MetricsBlockExtended"];
            equity_curve?: components["schemas"]["EquityPoint"][];
            trades?: components["schemas"]["Trade"][];
            signals?: components["schemas"]["Signal"][];
        };
        /** @description Aggregated across symbols (equal-weighted). */
        SummaryBlock: {
            metrics?: components["schemas"]["MetricsBlockExtended"];
            equity_curve?: components["schemas"]["EquityPoint"][];
            drawdown_curve?: components["schemas"]["EquityPoint"][];
            monthly_returns?: components["schemas"]["MonthlyPoint"][];
        };
        /** @description Extended metrics superset used by Deep Backtest + OptimLens. */
        MetricsBlockExtended: {
            total_return?: number | null;
            sharpe?: number | null;
            sortino?: number | null;
            calmar?: number | null;
            profit_factor?: number | null;
            win_rate?: number | null;
            avg_trade?: number | null;
            avg_hours_in_trade?: number | null;
            positive_days_ratio?: number | null;
            max_drawdown?: number | null;
            total_trades?: number;
        };
        /**
         * @description New multi-symbol + preview/deep backtest result shape. Replaces
         *     the single-mode `BacktestResult` for `startBacktest` + `getBacktestResult`.
         */
        BacktestResultExtended: {
            summary: components["schemas"]["SummaryBlock"];
            per_symbol: {
                [key: string]: components["schemas"]["SymbolResult"];
            };
        };
        StrategyVersion: {
            /** Format: uuid */
            strategy_id: string;
            version: number;
            code: string;
            summary?: string | null;
            params_schema?: {
                [key: string]: unknown;
            } | null;
            parent_version?: number | null;
            created_at: number;
        };
        OptimLensRequest: {
            /** Format: uuid */
            strategy_id: string;
            symbols: string[];
            lookback_days?: number;
            /** @description Map of param-name → list of values. Server computes the cross-product; rejected with PARAM_GRID_TOO_LARGE if > 50. */
            param_grid: {
                [key: string]: unknown[];
            };
        };
        OptimLensImprovement: {
            title: string;
            /** @enum {string} */
            category: "entry" | "exit" | "params" | "filter" | "risk_mgmt";
            rationale: string;
            expected_delta?: {
                sharpe?: number | null;
                max_drawdown?: number | null;
                win_rate?: number | null;
            };
            /** @description Either a param_update or a code_edit. */
            suggested_change?: {
                /** @enum {string} */
                kind?: "param_update" | "code_edit";
                payload?: {
                    [key: string]: unknown;
                };
            };
        };
        OptimLensResult: {
            base_metrics?: components["schemas"]["MetricsBlockExtended"];
            /** @description Per-combo metrics (one row per sub-backtest that ran). */
            grid_results?: {
                combo?: {
                    [key: string]: unknown;
                };
                metrics?: components["schemas"]["MetricsBlockExtended"];
            }[];
            improvements: components["schemas"]["OptimLensImprovement"][];
        };
        SignalReviewRequest: {
            /** Format: uuid */
            backtest_task_id: string;
        };
        SignalVerdict: {
            signal_id: string;
            symbol: string;
            entry_ts: number;
            /** @enum {string} */
            verdict: "good" | "questionable" | "bad";
            note?: string;
        };
        SignalReviewResult: {
            signals_total: number;
            verdicts: components["schemas"]["SignalVerdict"][];
            summary: {
                good?: number;
                questionable?: number;
                bad?: number;
            };
        };
        TradeExplainRequest: {
            /** Format: uuid */
            backtest_task_id: string;
            symbol: string;
            trade_id: string;
        } | {
            trade: components["schemas"]["Trade"];
            klines_context: components["schemas"]["Kline"][];
        };
        TradeExplainResult: {
            trade_id: string;
            narrative: string;
            entry_context?: {
                indicators?: {
                    [key: string]: number;
                };
                regime?: string;
            };
            exit_context?: {
                reason?: string;
                indicators?: {
                    [key: string]: number;
                };
            };
        };
        EngineStatus: {
            version: string;
            data_aggregator_version?: string | null;
            supported_markets: components["schemas"]["Market"][];
            supported_intervals: components["schemas"]["Interval"][];
            data_range?: {
                from?: number | null;
                to?: number | null;
            } | null;
            last_aggregator_sync_at?: number | null;
            active_tasks: number;
            uptime_seconds: number;
        };
        SymbolMetadata: {
            symbol: string;
            name?: string;
            market: components["schemas"]["Market"];
            rank?: number | null;
            volume_24h_quote?: number | null;
            last_price?: number | null;
            change_24h_pct?: number | null;
            first_kline_at?: number | null;
            last_kline_at?: number | null;
            /** @enum {string} */
            status: "active" | "inactive";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    getKlines: {
        parameters: {
            query: {
                symbol: string;
                interval: components["schemas"]["Interval"];
                from?: number;
                to?: number;
                market?: components["schemas"]["Market"];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered K-lines (ascending by ts) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Kline"][];
                };
            };
            /** @description Invalid parameters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listSymbols: {
        parameters: {
            query?: {
                market?: components["schemas"]["Market"];
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated symbols */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items: components["schemas"]["Symbol"][];
                    };
                };
            };
        };
    };
    listGaps: {
        parameters: {
            query?: {
                symbol?: string;
                interval?: components["schemas"]["Interval"];
                status?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching gaps */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Gap"][];
                };
            };
        };
    };
    listStrategies: {
        parameters: {
            query?: {
                code_type?: "strategy" | "screener";
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated strategies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items: components["schemas"]["Strategy"][];
                    };
                };
            };
        };
    };
    createStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    /** @enum {string} */
                    code_type: "strategy" | "screener";
                    code: string;
                    params_schema?: {
                        [key: string]: unknown;
                    };
                };
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        name: string;
                    };
                };
            };
        };
    };
    getStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strategy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patchStrategyDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchStrategyDraftBody"];
            };
        };
        responses: {
            /** @description Updated strategy (full envelope) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    saveStrategy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["SaveStrategyBody"];
            };
        };
        responses: {
            /** @description Updated strategy (full envelope) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Strategy"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    archiveStrategyDraft: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Acknowledgement payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        id: string;
                        is_archived_draft: boolean;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startBacktest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                    config: components["schemas"]["BacktestConfig"];
                    /** Format: uuid */
                    strategy_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Task accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation error or Gate 1 (AST compliance) rejection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description Gate 2 (AI review) rejected the submitted code.  `details`
             *     contains `{reason, model, dimensions: {security, correctness}}`.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /**
             * @description Gate 2 is enabled but the AI reviewer is temporarily unavailable
             *     (no API key, network, upstream error).  Retry later.
             */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getBacktestStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status envelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    getBacktestResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full result (embedded when status=done) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"] & {
                        result?: components["schemas"]["BacktestResult"];
                    };
                };
            };
        };
    };
    listBacktestHistory: {
        parameters: {
            query?: {
                strategy_id?: string;
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items: components["schemas"]["BacktestHistoryItem"][];
                    };
                };
            };
        };
    };
    startScreener: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                    config?: {
                        market?: components["schemas"]["Market"];
                        /** @default 365 */
                        lookback_days?: number;
                    };
                    /** Format: uuid */
                    strategy_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Task accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description Validation error or Gate 1 rejection */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gate 2 (AI review) rejected the submitted code. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Gate 2 reviewer temporarily unavailable. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getScreenerResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task envelope (result present when done) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"] & {
                        result?: components["schemas"]["ScreenerResult"];
                    };
                };
            };
        };
    };
    getSymbolMetadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Symbol metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SymbolMetadata"];
                };
            };
            /** @description Symbol not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listStrategyVersions: {
        parameters: {
            query?: {
                limit?: number;
                cursor?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated versions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items: components["schemas"]["StrategyVersion"][];
                    };
                };
            };
        };
    };
    createStrategyVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    code: string;
                    summary?: string;
                    params_schema?: {
                        [key: string]: unknown;
                    };
                    parent_version?: number;
                };
            };
        };
        responses: {
            /** @description New version */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersion"];
                };
            };
            /** @description Bad parent_version */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getStrategyVersion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Version payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyVersion"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    startOptimLens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimLensRequest"];
            };
        };
        responses: {
            /** @description Task accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
            /** @description param_grid too large */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getOptimLensResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task envelope (result present when done) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"] & {
                        result?: components["schemas"]["OptimLensResult"];
                    };
                };
            };
        };
    };
    startSignalReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignalReviewRequest"];
            };
        };
        responses: {
            /** @description Task accepted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"];
                };
            };
        };
    };
    getSignalReviewResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task envelope */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskResponse"] & {
                        result?: components["schemas"]["SignalReviewResult"];
                    };
                };
            };
        };
    };
    explainTrade: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TradeExplainRequest"];
            };
        };
        responses: {
            /** @description Trade explanation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TradeExplainResult"];
                };
            };
            /** @description LLM provider failed */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getEngineStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Engine status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineStatus"];
                };
            };
        };
    };
}
